name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 892004491300.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_URI=892004491300.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mediplus:$GITHUB_RUN_NUMBER
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI


          deploy:
            run:
                needs: build-push
                steps:
                    - name: check my ssh key
                      run: |
                        echo ${{ secrets.SSH_KEY }} > mykey.pem
                        chmod 600 mykey.pem
                        cat mykey.pem
                        