name: Build and Deploy to ECR and EC2

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        env:
          AWS_REGION: eu-north-1
          ECR_REGISTRY: 780139020397.dkr.ecr.eu-north-1.amazonaws.com
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 892004491300.dkr.ecr.eu-north-1.amazonaws.com
          IMAGE_NAME: mediplus
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Copy SSH key and connect to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > docker.pem
          chmod 600 docker.pem
          echo "Connecting to EC2 instance..."

          ssh -o StrictHostKeyChecking=no -i docker.pem ubuntu@3.90.219.251 "echo 'Connected to EC2'; docker ps"

          ssh -o StrictHostKeyChecking=no -i docker.pem ubuntu@3.90.219.251 << 'EOF'
          echo "Pulling latest image from ECR..."
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 892004491300.dkr.ecr.eu-north-1.amazonaws.com
          docker push 892004491300.dkr.ecr.eu-north-1.amazonaws.com/mediplus:latest
          echo "Stopping old container..."
          docker stop mediplus || true
          docker rm mediplus || true
          echo "Starting new container..."
          docker run -d -p 80:80 --name mediplus 892004491300.dkr.ecr.eu-north-1.amazonaws.com/mediplus:latest
          echo "Deployment complete."
          EOF