name: CI/CD Pipeline - Mediplus App

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Docker Image
      run: |
        IMAGE_URI=${{ secrets.REGISTRY_NAME }}/mediplus:$GITHUB_RUN_NUMBER
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI


  update-k8s-yaml:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    steps: 
    - name: clone-k8s-yaml repo
      env: 
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
        git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/digitalwitchdemo/kubernetes-manifest.git
        cd kubernetes-manifest/mediplus-yaml
        cat deployment.yaml

        sed -i "s+696035274327.dkr.ecr.eu-north-1.amazonaws.com/mediplus:.*+696035274327.dkr.ecr.eu-north-1.amazonaws.com/mediplus:$GITHUB_RUN_NUMBER+g" deployment.yaml
        cat deployment.yaml
        git config user.email support@digitalwitchng.online
        git config user.name ${GIT_USERNAME}
        git add .
        git commit -m "Updated the k8s.yaml with new image tag"
        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/digitalwitchdemo/kubernetes-manifest.git HEAD:main
        
      
    
      
     
